//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylverInk.Localization
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SylverInk.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Colors.
        /// </summary>
        public static string AccentColors {
            get {
                return ResourceManager.GetString("AccentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive notes:.
        /// </summary>
        public static string AdaptiveNotes {
            get {
                return ResourceManager.GetString("AdaptiveNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to automatically detect boundaries between notes..
        /// </summary>
        public static string AdaptiveNotesTooltip {
            get {
                return ResourceManager.GetString("AdaptiveNotesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Code:.
        /// </summary>
        public static string AddressCode {
            get {
                return ResourceManager.GetString("AddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet List.
        /// </summary>
        public static string BulletList {
            get {
                return ResourceManager.GetString("BulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of time (in seconds) a transparent sticky note must be hovered over before it activates..
        /// </summary>
        public static string ClickthroughTooltip {
            get {
                return ResourceManager.GetString("ClickthroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to network.
        /// </summary>
        public static string CloseToNetwork {
            get {
                return ResourceManager.GetString("CloseToNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this note?.
        /// </summary>
        public static string ConfirmDeleteNote {
            get {
                return ResourceManager.GetString("ConfirmDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a code generated by the Sylver Ink server..
        /// </summary>
        public static string ConnectLabelTooltip {
            get {
                return ResourceManager.GetString("ConnectLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content preview.
        /// </summary>
        public static string ContentPreview {
            get {
                return ResourceManager.GetString("ContentPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address code.
        /// </summary>
        public static string CopyAddressCode {
            get {
                return ResourceManager.GetString("CopyAddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load database: {0}.
        /// </summary>
        public static string CouldNotLoadDatabase {
            get {
                return ResourceManager.GetString("CouldNotLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color....
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sylver Ink backup files (*.sibk)|*.sibk|Sylver Ink database files (*.sidb)|*.sidb|Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string DatabaseAndTextFileFilter {
            get {
                return ResourceManager.GetString("DatabaseAndTextFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sylver Ink backup files (*.sibk)|*.sibk|Sylver Ink database files (*.sidb)|*.sidb|All files (*.*)|*.*.
        /// </summary>
        public static string DatabaseFileFilter {
            get {
                return ResourceManager.GetString("DatabaseFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialized database has exceeded the maximum capacity for restricted LZW compression..
        /// </summary>
        public static string DatabaseTooLargeForCompression {
            get {
                return ResourceManager.GetString("DatabaseTooLargeForCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program attempted to load a database file with a newer format than it supports..
        /// </summary>
        public static string DatabaseTooNew {
            get {
                return ResourceManager.GetString("DatabaseTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Font Size.
        /// </summary>
        public static string DecreaseFontSize {
            get {
                return ResourceManager.GetString("DecreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default color.
        /// </summary>
        public static string DefaultColor {
            get {
                return ResourceManager.GetString("DefaultColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DefaultDatabase {
            get {
                return ResourceManager.GetString("DefaultDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Font.
        /// </summary>
        public static string DisplayFont {
            get {
                return ResourceManager.GetString("DisplayFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty note).
        /// </summary>
        public static string EmptyNote {
            get {
                return ResourceManager.GetString("EmptyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry last modified:.
        /// </summary>
        public static string EntryLastModified {
            get {
                return ResourceManager.GetString("EntryLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of Sylver Ink is already running..
        /// </summary>
        public static string Error_InstanceRunning {
            get {
                return ResourceManager.GetString("Error_InstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit Sylver Ink?.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your work before exiting?.
        /// </summary>
        public static string ExitMessage_SaveWork {
            get {
                return ResourceManager.GetString("ExitMessage_SaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to autodetect the note format..
        /// </summary>
        public static string FailedAutodetect {
            get {
                return ResourceManager.GetString("FailedAutodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the database..
        /// </summary>
        public static string FailedConnection {
            get {
                return ResourceManager.GetString("FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the DNS server. Please try again..
        /// </summary>
        public static string FailedDNSConnection {
            get {
                return ResourceManager.GetString("FailedDNSConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the selected file..
        /// </summary>
        public static string FailedImport {
            get {
                return ResourceManager.GetString("FailedImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the database server on port {0}..
        /// </summary>
        public static string FailedToOpenServer {
            get {
                return ResourceManager.GetString("FailedToOpenServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process file: {0}.
        /// </summary>
        public static string FailedToProcessFile {
            get {
                return ResourceManager.GetString("FailedToProcessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file..
        /// </summary>
        public static string FailedToReadFile {
            get {
                return ResourceManager.GetString("FailedToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to import.
        /// </summary>
        public static string FileToImport {
            get {
                return ResourceManager.GetString("FileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex code (RGB or ARGB).
        /// </summary>
        public static string HexCodeTooltip {
            get {
                return ResourceManager.GetString("HexCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated new notes: {0}\nAverage length: {1} characters per note\n\nRemember to press Import to finalize your changes!.
        /// </summary>
        public static string Import_MeasurementText {
            get {
                return ResourceManager.GetString("Import_MeasurementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imported.
        /// </summary>
        public static string Imported {
            get {
                return ResourceManager.GetString("Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the selected file: {0}.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        public static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Font Size.
        /// </summary>
        public static string IncreaseFontSize {
            get {
                return ResourceManager.GetString("IncreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index number.
        /// </summary>
        public static string IndexNumber {
            get {
                return ResourceManager.GetString("IndexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string Justify {
            get {
                return ResourceManager.GetString("Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changed date.
        /// </summary>
        public static string LastChangedDate {
            get {
                return ResourceManager.GetString("LastChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line tolerance:.
        /// </summary>
        public static string LineTolerance {
            get {
                return ResourceManager.GetString("LineTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of blank lines to look for when separating the file into different notes..
        /// </summary>
        public static string LineToleranceTooltip {
            get {
                return ResourceManager.GetString("LineToleranceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest note:.
        /// </summary>
        public static string LongestNote {
            get {
                return ResourceManager.GetString("LongestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring....
        /// </summary>
        public static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Colors.
        /// </summary>
        public static string MenuColors {
            get {
                return ResourceManager.GetString("MenuColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this database?.
        /// </summary>
        public static string Message_ConfirmDeleteDatabase {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revert the database to the selected date and time?.
        /// </summary>
        public static string Message_ConfirmReversion {
            get {
                return ResourceManager.GetString("Message_ConfirmReversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - The database last closed unexpectedly. Do you want to load the most recent autosave?.
        /// </summary>
        public static string Message_DatabaseAutosaved {
            get {
                return ResourceManager.GetString("Message_DatabaseAutosaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database already exists with the provided name..
        /// </summary>
        public static string Message_DatabaseExists {
            get {
                return ResourceManager.GetString("Message_DatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database was created in a newer format than the current version of Sylver Ink supports. Please update your installation before opening this database..
        /// </summary>
        public static string Message_DatabaseTooNew {
            get {
                return ResourceManager.GetString("Message_DatabaseTooNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} has been either moved or deleted.\n\nDo you want to remove it from the list?.
        /// </summary>
        public static string Message_FileMovedOrDeleted {
            get {
                return ResourceManager.GetString("Message_FileMovedOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address code. Must be 6 characters..
        /// </summary>
        public static string Message_InvalidAddressCode {
            get {
                return ResourceManager.GetString("Message_InvalidAddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided name contains invalid character: {0}.
        /// </summary>
        public static string Message_InvalidPath {
            get {
                return ResourceManager.GetString("Message_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected an existing Sylver Ink database. Its contents will be merged with your current database.\n\nDo you want to overwrite your current database instead?.
        /// </summary>
        public static string Message_MergeDatabases {
            get {
                return ResourceManager.GetString("Message_MergeDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Save before closing this note?.
        /// </summary>
        public static string Message_SaveBeforeClosingNote {
            get {
                return ResourceManager.GetString("Message_SaveBeforeClosingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string Message_SaveChangesShort {
            get {
                return ResourceManager.GetString("Message_SaveChangesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Sylver Ink is available ({0} → {1}).\n\nWould you like to download and install it now?.
        /// </summary>
        public static string Message_UpdateAvailable {
            get {
                return ResourceManager.GetString("Message_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SylverInk.msi.
        /// </summary>
        public static string MsiFileName {
            get {
                return ResourceManager.GetString("MsiFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New note.
        /// </summary>
        public static string NewNote {
            get {
                return ResourceManager.GetString("NewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a line of text and press Enter to create a new note. You can also press Ctrl+N to open a sticky note at any time..
        /// </summary>
        public static string NewNoteTooltip {
            get {
                return ResourceManager.GetString("NewNoteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next....
        /// </summary>
        public static string NextEllipsis {
            get {
                return ResourceManager.GetString("NextEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry created: {0}.
        /// </summary>
        public static string Note_EntryCreated {
            get {
                return ResourceManager.GetString("Note_EntryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry last modified: {0}.
        /// </summary>
        public static string Note_EntryModified {
            get {
                return ResourceManager.GetString("Note_EntryModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision {0} from.
        /// </summary>
        public static string Note_RevisionID {
            get {
                return ResourceManager.GetString("Note_RevisionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note count:.
        /// </summary>
        public static string NoteCount {
            get {
                return ResourceManager.GetString("NoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note locked by another user.
        /// </summary>
        public static string NoteLocked {
            get {
                return ResourceManager.GetString("NoteLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes imported: {0}.
        /// </summary>
        public static string NotesImported {
            get {
                return ResourceManager.GetString("NotesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered List.
        /// </summary>
        public static string NumberedList {
            get {
                return ResourceManager.GetString("NumberedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recent.
        /// </summary>
        public static string OpenRecent {
            get {
                return ResourceManager.GetString("OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open to network.
        /// </summary>
        public static string OpenToNetwork {
            get {
                return ResourceManager.GetString("OpenToNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous....
        /// </summary>
        public static string PreviousEllipsis {
            get {
                return ResourceManager.GetString("PreviousEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent notes.
        /// </summary>
        public static string RecentNotes {
            get {
                return ResourceManager.GetString("RecentNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can press Ctrl+L to re-open the note you most recently closed..
        /// </summary>
        public static string RecentNotesTooltip {
            get {
                return ResourceManager.GetString("RecentNotesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database with that name already exists in {0}.\n\nDo you want to overwrite it?.
        /// </summary>
        public static string Rename_DatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("Rename_DatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Documents.
        /// </summary>
        public static string SaveToDocuments {
            get {
                return ResourceManager.GetString("SaveToDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Scanned {
            get {
                return ResourceManager.GetString("Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to import..
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter this code in another Sylver Ink installation to connect to the database..
        /// </summary>
        public static string ServerCodeLabelTooltip {
            get {
                return ResourceManager.GetString("ServerCodeLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.sis.
        /// </summary>
        public static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string Subfolder_Databases {
            get {
                return ResourceManager.GetString("Subfolder_Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sylver Ink.
        /// </summary>
        public static string SylverInk {
            get {
                return ResourceManager.GetString("SylverInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No converter registered for {0}.
        /// </summary>
        public static string Text_NoConverterRegistered {
            get {
                return ResourceManager.GetString("Text_NoConverterRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parser registered for {0}.
        /// </summary>
        public static string Text_NoParserRegistered {
            get {
                return ResourceManager.GetString("Text_NoParserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saver registered for {0}.
        /// </summary>
        public static string Text_NoSaverRegistered {
            get {
                return ResourceManager.GetString("Text_NoSaverRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color....
        /// </summary>
        public static string TextColorEllipsis {
            get {
                return ResourceManager.GetString("TextColorEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Colors.
        /// </summary>
        public static string TextColors {
            get {
                return ResourceManager.GetString("TextColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sylver Ink: Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sylver Ink: Notification.
        /// </summary>
        public static string Title_Notification {
            get {
                return ResourceManager.GetString("Title_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sylver Ink: Warning.
        /// </summary>
        public static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy the address code to the clipboard.
        /// </summary>
        public static string Tooltip_FailedCopy {
            get {
                return ResourceManager.GetString("Tooltip_FailedCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total length:.
        /// </summary>
        public static string TotalLength {
            get {
                return ResourceManager.GetString("TotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load database file: {0}.
        /// </summary>
        public static string UnableToLoadDatabase {
            get {
                return ResourceManager.GetString("UnableToLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Sylver Ink: {0}.
        /// </summary>
        public static string UnableToUpdate {
            get {
                return ResourceManager.GetString("UnableToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View....
        /// </summary>
        public static string ViewEllipsis {
            get {
                return ResourceManager.GetString("ViewEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Word_About {
            get {
                return ResourceManager.GetString("Word_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Word_Backup {
            get {
                return ResourceManager.GetString("Word_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup....
        /// </summary>
        public static string Word_BackupEllipsis {
            get {
                return ResourceManager.GetString("Word_BackupEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chars.
        /// </summary>
        public static string Word_Chars {
            get {
                return ResourceManager.GetString("Word_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Word_Close {
            get {
                return ResourceManager.GetString("Word_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Word_Connect {
            get {
                return ResourceManager.GetString("Word_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Word_Copy {
            get {
                return ResourceManager.GetString("Word_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Word_Database {
            get {
                return ResourceManager.GetString("Word_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Word_Delete {
            get {
                return ResourceManager.GetString("Word_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Word_Disconnect {
            get {
                return ResourceManager.GetString("Word_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Word_Exit {
            get {
                return ResourceManager.GetString("Word_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Word_Help {
            get {
                return ResourceManager.GetString("Word_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Word_Import {
            get {
                return ResourceManager.GetString("Word_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Word_Network {
            get {
                return ResourceManager.GetString("Word_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Word_Note {
            get {
                return ResourceManager.GetString("Word_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string Word_Notes {
            get {
                return ResourceManager.GetString("Word_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Word_Open {
            get {
                return ResourceManager.GetString("Word_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Word_OpenEllipsis {
            get {
                return ResourceManager.GetString("Word_OpenEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Word_Properties {
            get {
                return ResourceManager.GetString("Word_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Word_Redo {
            get {
                return ResourceManager.GetString("Word_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Word_Rename {
            get {
                return ResourceManager.GetString("Word_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Word_Save {
            get {
                return ResourceManager.GetString("Word_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Word_Search {
            get {
                return ResourceManager.GetString("Word_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Word_Settings {
            get {
                return ResourceManager.GetString("Word_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Word_Undo {
            get {
                return ResourceManager.GetString("Word_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words.
        /// </summary>
        public static string Word_Words {
            get {
                return ResourceManager.GetString("Word_Words", resourceCulture);
            }
        }
    }
}
